version: "3.8"

services:
  # react:

  # app:
  #   depends_on:
  #     - db

  db:
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - server/.env

volumes:
  db_data:
