version: "3.8"

services:
  front:
    build: ./courier_app
    ports:
      - 3000:3000

  app:
    build: ./server
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - server/.env

volumes:
  db_data:
